services:
  web:
    image: thanhtunguet/ttdn:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - ttdn
    command: yarn start:prod
networks:
  ttdn:
    driver: bridge
